# Generated by Django 5.2.7 on 2025-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('card_last4', models.CharField(max_length=4)),
                ('merchant', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['transaction_id'], name='fraud_app_t_transac_713f81_idx'), models.Index(fields=['is_flagged'], name='fraud_app_t_is_flag_456016_idx')],
            },
        ),
    ]
